name: 'earthquake_analytics'
version: '1.0.0'
config-version: 2

profile: 'earthquake_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  database: USER_DB_PLATYPUS
  raw_schema: RAW
  analytics_schema: ANALYTICS

models:
  earthquake_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: incremental
      +on_schema_change: append_new_columns