version: 2

models:
  - name: stg_earthquakes
    description: "Cleaned and standardized earthquake data with derived fields"
    columns:
      - name: event_id
        description: "Primary key - unique earthquake event identifier"
        tests:
          - unique
          - not_null
      - name: magnitude
        description: "Earthquake magnitude"
        tests:
          - not_null
      - name: magnitude_category
        description: "Categorical classification of magnitude (micro, minor, light, moderate, strong, major, great)"
      - name: latitude
        description: "Latitude of earthquake epicenter"
        tests:
          - not_null
      - name: longitude
        description: "Longitude of earthquake epicenter"
        tests:
          - not_null
      - name: depth_km
        description: "Depth of the earthquake in kilometers"
      - name: depth_category
        description: "Categorical depth (shallow, intermediate, deep)"
      - name: region
        description: "Extracted region name from place description"
      - name: event_timestamp
        description: "Timestamp of the earthquake event"
        tests:
          - not_null
      - name: event_date
        description: "Date of the earthquake"
      - name: has_tsunami_warning
        description: "Boolean indicating if tsunami warning was issued"
