import{FEED,normalize,filterEvents,stats,csv}from'./data.mjs';
const $=s=>document.querySelector(s),esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const utc=t=>new Date(t).toISOString().replace('T',' ').slice(0,19)+' UTC';
let data=null,mode='live',visible=[],limit=30,map=null,markers=null,request=0;
if(window.L){map=L.map('map',{scrollWheelZoom:false}).setView([20,0],2);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors © CARTO',maxZoom:18}).addTo(map).on('tileerror',()=>{$('#map-note').textContent='Some map tiles are unavailable. Event markers and the table still work.';});markers=L.layerGroup().addTo(map);}else{$('#map').textContent='Map unavailable. Explore events in the table below.';}
async function fetchJSON(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(url,{signal:c.signal,cache:'no-cache'});if(!r.ok)throw new Error('Feed unavailable');return normalize(await r.json());}finally{clearTimeout(t);}}
async function load(){const id=++request;$('#refresh').disabled=true;$('#status').textContent='Loading earthquake observations…';$('#status').className='status';let fallback=false,nextMode=$('#source').value,nextData;try{try{nextData=await fetchJSON(nextMode==='live'?FEED:'snapshot.json');}catch(e){if(nextMode==='snapshot')throw e;nextData=await fetchJSON('snapshot.json');nextMode='snapshot';fallback=true;}if(id!==request)return;data=nextData;mode=nextMode;
 const age=Date.now()-data.generated,stale=mode==='live'&&age>15*60000;
 $('#status').className='status'+(mode==='snapshot'||stale?' snapshot':'');
 $('#status').textContent=(mode==='snapshot'?(fallback?'USGS unavailable · ':'')+'Saved snapshot — not live. ':'Latest retrieved USGS feed'+(stale?' — feed is delayed. ':'. '))+'Generated '+utc(data.generated)+'. '+(mode==='snapshot'?'Time filters are relative to this snapshot.':'Time filters are relative to now.');
 $('#quality').textContent=`${data.input.toLocaleString()} source records · ${data.events.length.toLocaleString()} accepted events · ${data.rejected} rejected · ${data.duplicates} duplicate records removed.`;
 $('#detail').innerHTML='<h2>Select an earthquake</h2><p>Choose a map circle or Inspect in the table.</p>';limit=30;render();
 }catch(e){if(id!==request)return;data=null;visible=[];$('#status').className='status error';$('#status').textContent='Could not load the feed or saved snapshot. Please retry.';$('#quality').textContent='No data loaded.';$('#detail').replaceChildren();render();}finally{if(id===request)$('#refresh').disabled=false;}}
function inspect(e){$('#detail').innerHTML=`<div class="detail-mag">${e.mag===null?'—':'M '+e.mag.toFixed(1)}</div><h2>${esc(e.place)}</h2><p>${utc(e.time)}</p><dl><dt>Depth</dt><dd>${e.depth===null?'Unknown':e.depth.toFixed(1)+' km'}</dd><dt>Magnitude type</dt><dd>${esc(e.magType)}</dd><dt>Latitude</dt><dd>${e.lat.toFixed(3)}°</dd><dt>Longitude</dt><dd>${e.lon.toFixed(3)}°</dd><dt>Status</dt><dd>${esc(e.status)}</dd><dt>Event ID</dt><dd>${esc(e.id)}</dd></dl><p class="small">Revised ${utc(e.updated)}</p>${e.url?`<a href="${esc(e.url)}" target="_blank" rel="noopener">View USGS source ↗</a>`:''}`;if(map)map.panTo([e.lat,e.lon]);}
function render(){const minimum=Number($('#magnitude').value);$('#mag-value').textContent=minimum===-2?'All':minimum.toFixed(1)+'+';visible=data?filterEvents(data.events,{hours:Number($('#window').value),minimum,query:$('#search').value,anchor:mode==='snapshot'?data.generated:Date.now()}):[];const s=stats(visible);$('#count').textContent=s.count.toLocaleString();$('#largest').textContent=s.largest===null?'—':s.largest.toFixed(1);$('#depth').textContent=s.depth===null?'—':s.depth.toFixed(1)+' km';$('#strong').textContent=s.strong.toLocaleString();$('#download').disabled=!visible.length;
 if(markers){markers.clearLayers();for(const e of visible)L.circleMarker([e.lat,e.lon],{radius:Math.max(3,Math.min(15,3+(e.mag??0)*1.6)),weight:1,color:e.mag>=5?'#be4932':'#315ce9',fillOpacity:.45}).on('click',()=>inspect(e)).addTo(markers);}
 const buckets=[['Below 2',e=>e.mag!==null&&e.mag<2],['2–3.9',e=>e.mag>=2&&e.mag<4],['4–4.9',e=>e.mag>=4&&e.mag<5],['5+',e=>e.mag>=5],['Unknown',e=>e.mag===null]].map(([name,p])=>[name,visible.filter(p).length]),max=Math.max(1,...buckets.map(x=>x[1]));$('#histogram').innerHTML=buckets.map(([name,n])=>`<div class="bar-row"><span>${name}</span><div class="bar-track"><span style="width:${n/max*100}%"></span></div><span>${n}</span></div>`).join('');renderTable();}
function renderTable(){$('#events').replaceChildren();for(const e of visible.slice(0,limit)){const row=document.createElement('tr');row.innerHTML=`<td>${utc(e.time).replace(' UTC','')}</td><td>${esc(e.place)}</td><td>${e.mag===null?'Unknown':e.mag.toFixed(1)}</td><td>${e.depth===null?'Unknown':e.depth.toFixed(1)+' km'}</td><td><button>Inspect</button></td>`;row.querySelector('button').setAttribute('aria-label','Inspect '+e.place);row.querySelector('button').onclick=()=>inspect(e);$('#events').append(row);}$('#table-note').textContent=visible.length?`Showing ${Math.min(limit,visible.length)} of ${visible.length} filtered events, newest first.`:'No events match these filters.';$('#more').hidden=limit>=visible.length;}
for(const id of ['#window','#magnitude','#search'])$(id).addEventListener('input',()=>{limit=30;render();});$('#source').onchange=load;$('#refresh').onclick=load;$('#reset').onclick=()=>{$('#window').value='24';$('#magnitude').value='-2';$('#search').value='';limit=30;render();};$('#more').onclick=()=>{limit+=50;renderTable();};$('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([csv(visible)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='earthquakes-'+mode+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};load();
